spring.application.name=APP.Tesis
server.port=8080

# ===============================
# Configuración de PostgreSQL
# ===============================
# IMPORTANTE: Cambia "bd_tesis" por el nombre exacto que le pusiste a tu base de datos en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_tesis
spring.datasource.driverClassName=org.postgresql.Driver

# Tu usuario de Postgres (casi siempre es "postgres")
spring.datasource.username=postgres

# IMPORTANTE: Pon aquí la contraseña que creaste al instalar PostgreSQL
spring.datasource.password=Tesis12345

# ===============================
# Configuración de JPA/Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# "update" creará las tablas si no existen y las actualizará si añades nuevos campos en Java
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (útil para ver qué hace Hibernate por detrás)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Configuración de Seguridad
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin123